### ISSUE TITLE
New flatpack issue

### ISSUE THREAD

**Issue by edpil02** [timlau/yumex-ng#101]
After downloading the latest version of yumex, I wanted to do a test with flatpak by searching for Firefox but each time I get this error:

09:36:30 DEBUG : (yumex) -  (flatpak_seach) key: fire  location: system
09:36:30 DEBUG : (yumex) -   found : Firefox - Navigateur Web (app/org.mozilla.Firefox/x86_64/stable) match: 1
09:36:30 DEBUG : (yumex) -   found : Firefox - Navigateur Web (app/org.mozilla.firefox/x86_64/stable) match: 1
09:36:30 DEBUG : (yumex) -   found : Pare-feu - Configuration du pare-feu (app/org.fedoraproject.FirewallConfig/x86_64/stable) match: 2
09:36:30 DEBUG : (yumex) -   found : GNU IceCat - GNU version of Firefox browser (app/org.gnu.icecat/x86_64/stable) match: 3
09:36:30 CRITICAL: (yumex) -  Uncaught exception: 'NoneType' object has no attribute 'get_version'
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/yumex/ui/flatpak_search.py", line 146, in on_bind
    version = pkg.version
              ^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/yumex/backend/flatpak/search.py", line 61, in version
    version = releases.index_safe(0).get_version()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_version'
09:36:30 DEBUG : (yumex) -  traceback written to /home/edmond/.local/share/yumex/traceback_07-30-2024_093630.txt
09:36:30 CRITICAL: (yumex) -  Uncaught exception: 'NoneType' object has no attribute 'get_version'
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/yumex/ui/flatpak_search.py", line 146, in on_bind
    version = pkg.version
              ^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/yumex/backend/flatpak/search.py", line 61, in version
    version = releases.index_safe(0).get_version()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_version'

**Comment by timlau** [comment]
Think I have found the issues and fixed it, new dev-build with the fix will be created tommorow

**Comment by timlau** [comment]
Fix contained in 5.0.3-0.1.git20240808 build
https://copr.fedorainfracloud.org/coprs/timlau/yumex-ng-dev/builds/

**Comment by edpil02** [comment]
just did a test and it's solved .
![yumex](https://github.com/user-attachments/assets/42e24e5c-2ee2-4c94-ae89-0e2219d0aa41)

Thanks
