### ISSUE TITLE
Crash with dnf  "fastestmirror"  option

### ISSUE THREAD

**Issue by edpil02** [timlau/yumex-ng#104]
I'm using  yumex-ng-dev latest rawhide build.
I added "fastestmirror" in my dnf.conf to improve my connections but yumex seems not to support it.
Disable the option help the issue.

Yumex search   .cache/libdnf5/fastestmirror.cache/attrs  directory.
But only  .cache/libdnf5/fastestmirror.cache   file exist.

09:15:03 DEBUG : (yumex) -  DNF5: current cachedir : /home/edmond/.cache/libdnf5
09:15:03 DEBUG : (yumex) -  DNF5: expire repo loacted at /home/edmond/.cache/libdnf5/rpmfusion-free-rawhide-11a4e834e18e3a11
09:15:03 DEBUG : (yumex) -  DNF5: expire repo loacted at /home/edmond/.cache/libdnf5/fastestmirror.cache
09:15:03 DEBUG : (yumex) -  Error while running async job: <bound method YumexPresenter.get_packages_by_filter of <yumex.backend.presenter.YumexPresenter object at 0x7f65bcbc2a50>>
Exception: filesystem error: cannot create directory: N'est pas un dossier [/home/edmond/.cache/libdnf5/fastestmirror.cache/attrs]
  File "/usr/lib/python3.13/site-packages/yumex/utils/__init__.py", line 73, in target
    result = self.task_func(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/yumex/backend/presenter.py", line 121, in get_packages_by_filter
    return self.package_cache.get_packages_by_filter(pkgfilter, reset)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/yumex/backend/cache.py", line 24, in get_packages_by_filter
    pkgs = self.get_packages(self.backend.get_packages(pkgfilter))
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/yumex/backend/dnf/dnf5.py", line 250, in get_packages
    self.expire_metadata()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/yumex/backend/dnf/dnf5.py", line 191, in expire_metadata
    repo_cache.write_attribute(RepoCache.ATTRIBUTE_EXPIRED)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/site-packages/libdnf5/repo.py", line 793, in write_attribute
    return _repo.RepoCache_write_attribute(self, *args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^

**Comment by timlau** [comment]
Should be fixed in latest build
https://copr.fedorainfracloud.org/coprs/timlau/yumex-ng-dev/build/7925417/

**Comment by edpil02** [comment]
Fixed. 
Thanks.
