### ISSUE TITLE
Add flatpak support

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-ng#14]
Add basic support for flatpaks

- [x] show installed flatpaks with origin and locatioon (user/system)
- [x] update installed flatpaks
- [x] remove flatpaks
- [x] install flatpaks 
- [x] handle **flatpak install flathub someid**  cmds in clipboard, copied from flathub.org

**Comment by legacychimera247** [comment]
hello, maybe we should reopen this?i'm on fedora 38 and removing a flatpak does nothing...
