### ISSUE TITLE
NoneType' object has no attribute 'get_string'

### ISSUE THREAD

**Issue by Framelony** [timlau/yumex-ng#16]
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yumex/ui/preferences.py", line 103, in on_source_notify
    source = self.fp_source.get_selected_item().get_string()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_string'

**Comment by timlau** [comment]
Thanks for reporting, fixed now, made a new copr build including the fix
