### ISSUE TITLE
Preferences menu error

### ISSUE THREAD

**Issue by edpil02** [timlau/yumex-ng#22]
I made a  build  with dnf5 , seems usable, but preferences  menu crash:

14:13:37 CRITICAL: (yumex) -  Uncaught exception: 'NoneType' object has no attribute 'get_string'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yumex/ui/preferences.py", line 96, in on_remote_selected
    remote = self.fp_remote.get_selected_item().get_string()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_string'

Thanks.

**Comment by timlau** [comment]
thanks for reporting
Look like a case where there is no remotes for a selected install location

**Comment by timlau** [comment]
@edpil02 the problem should be fixes now.

Note: the dnf5 backend works find for reading packagesm searching etc. but parts to apply to process the transaction is still using dnfdaemon there is using the dnf4 API.
The dnf5daemon is not working for me yet

https://github.com/rpm-software-management/dnf5/issues/229

**Comment by edpil02** [comment]
Issue fixed.
Thanks.
