### ISSUE TITLE
Table gui usability

### ISSUE THREAD

**Issue by grgendron** [timlau/yumex-ng#23]
Main table in gui is too small, should be expandable or larger. When adjusting column widths to read contents, end columns simply disappear.
![yumex-ng_2023-02-07](https://user-images.githubusercontent.com/7870326/217298468-5fa4c2f8-620c-47d7-b039-26f45e2a65dc.png)

**Comment by timlau** [comment]
The size of the main table is set to the sum of column widths from when it was closed last time.
so if you make the first column wider and close yumex and start it again, the main table will be larger.
I will look into making it more dynamic in the future.

**Comment by timlau** [comment]
I have made some changes in the lastest copr build, the width is now set from the saved window widrh.
So if you size the windows, to the prefered size and close it.
Next time your start then window size will be the same, but the table with should match the window size.
note: maximize & fullscreen are special cases, the don't change the original window size and will not effect the size of the table.

**Comment by RedSnt** [comment]
I know this is an old and closed issue, but would be nice if the flatpaks and queue tab followed the same rule as the package tab for resizing.
