### ISSUE TITLE
didnt install any keys

### ISSUE THREAD

**Issue by Mergpijp** [timlau/yumex-ng#24]
I updated my system with this  yum extender as package manager. The problem is if I try to update it says: didnt install any keys. I know there should be a dialog and I have to press Y but that is impossible here. Any help appreciated im running Nobara.

**Comment by timlau** [comment]
yumex-ng don't support installing new package GPG keys yets.

typical it is when adding a new copr repo this is needed, 
just use `sudo dnf update` to install the keys, and you can use yumex after that

**Comment by timlau** [comment]
See issue #13
