### ISSUE TITLE
Dnf5 build 

### ISSUE THREAD

**Issue by edpil02** [timlau/yumex-ng#30]
It looks like rawhide will switch to dnf5 . Is yumex-ng ready be rebuild with dnf5.
Thanks.

**Comment by timlau** [comment]
The GUI stuff is ready, but the backend doing the installation is based on dnfdaemon, that is based on dnf4 even when the gui part are using the dnf5 api.

I need to make a backend using a the dnf5 dbus api, I have done some api testing and found some issues with the API, but they should be fixed now in my latest tests.

As the GUI parts is pretty stable now, I hope to get some time to working on building an dnf5 backend for doing  the real work of installing, update and remove packages on the system.

**Comment by timlau** [comment]
I have add then basic part for a dnf5 based root backend for adding changes to the system and it works fine.
Just need to add progress and handle the corner cases, like gpg import and error checking.

When I get the last parts completed, I will create a yumex-dnf5 package to people can install both a dnf4 based and a dnf5 based version, when dnf5 become default in fedora release, the yumex package will be the dnf5 version.

**Comment by edpil02** [comment]
Good news.
Thanks    a lot.

**Comment by timlau** [comment]
Latest build for rawhide is using dnf5

https://copr.fedorainfracloud.org/coprs/timlau/yumex-ng/build/5972601/
