### ISSUE TITLE
Packages  are not checked  when select all

### ISSUE THREAD

**Issue by edpil02** [timlau/yumex-ng#33]
On update , when all packages are selected  ( Ctrl+A)  ,  none is checked even the queue is filled.
On the other hand  check uncheck  perform for individual package.

**Comment by timlau** [comment]
I tested with this build on F38

yumex:

yumex-dnf5.noarch 4.99.5-0.1.git20230604.fc38 copr:copr.fedorainfracloud.org:timlau:yumex-ng

DNF5:

Installed packages
dnf5.x86_64                                  5.0.13-2.fc38               <unknown>
dnf5daemon-server.x86_64                     5.0.13-2.fc38               <unknown>
libdnf5.x86_64                               5.0.13-2.fc38               <unknown>
libdnf5-cli.x86_64                           5.0.13-2.fc38               <unknown>
python3-libdnf5.x86_64                       5.0.13-2.fc38               <unknown>

**Comment by edpil02** [comment]
Rawhide  is  still  with dnf5   5.0.11-3.fc39   version .May be the  problem.
I didn't want to upgrade from koji .  But  after 5.0.12  , once again  i don't know  why , they are  again  delaying the update.
Tanks.

**Comment by timlau** [comment]
I can reproduce it on Fedora 39 - Beta with DNF5 based build from copr 

https://copr.fedorainfracloud.org/coprs/timlau/yumex-ng/build/6422010/

I will look into it

**Comment by timlau** [comment]
Fixed in latest yumex-dnf5 builds for F8 & F39

https://copr.fedorainfracloud.org/coprs/timlau/yumex-ng/build/6691913/
