### ISSUE TITLE
Yumex dnf5  still requires dnf4 dependencies.

### ISSUE THREAD

**Issue by edpil02** [timlau/yumex-ng#34]
$ yumex
Traceback (most recent call last):
 File "/usr/bin/yumex", line 67, in <module>
 from yumex import main
 File "/usr/lib/python3.11/site-packages/yumex/main.py", line 28, in <module>
 from yumex.ui.window import YumexMainWindow
 File "/usr/lib/python3.11/site-packages/yumex/ui/window.py", line 31, in <module>
 from yumex.ui.package_info import YumexPackageInfo
 File "/usr/lib/python3.11/site-packages/yumex/ui/package_info.py", line 16, in <module>
 import hawkey
ModuleNotFoundError: No module named 'hawkey'

$ sudo dnf install python3-hawkey
Updating and loading repositories:
Repositories loaded.
Package                                            Arch        Version                                      Repository                    Size
Installing:                                                                                                                             
python3-hawkey                          x86_64      0.70.1-3.fc39                                rawhide                  318.7 KiB
Installing dependencies:                                                                                                                
libdnf                                              x86_64      0.70.1-3.fc39                                rawhide                    2.0 MiB
python3-libdnf                              x86_64      0.70.1-3.fc39                                rawhide                    3.8 MiB

$ yumex
(process:15419): Gtk-WARNING **: 11:35:58.705: Unknown key gtk-modules in /home/edmond/.config/gtk-4.0/settings.ini
(process:15419): Adwaita-WARNING **: 11:35:58.713: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
11:35:58 DEBUG : (yumex) -  Version:  4.99.4-git20230608 (DNF5)
11:35:58 DEBUG : (yumex) -  executable : /usr/bin/yumex
11:35:58 DEBUG : (yumex) -  commmand-line : Namespace(debug=False, exit=False)
11:35:58 DEBUG : (yumex) -  set_need_attetion (flatpak): state: False

**Comment by timlau** [comment]
Thanks for reporting, i have fixed it now
https://copr.fedorainfracloud.org/coprs/timlau/yumex-ng/build/6084880/

Side note: Update advisory is now implemented in the DNF5 backend yet
