### ISSUE TITLE
flatpak install: toggling user->system->user does not re-disable available remotes

### ISSUE THREAD

**Issue by GloriousEggroll** [timlau/yumex-ng#40]
If the system has a list of remotes, and there are no remotes available for user, by default the remote dropdown is disabled for user. If you swap it to system then back to user, it allows attempting to search the system remotes with user defined (ultimately causing a crash)

![Screenshot from 2023-06-23 19-19-49](https://github.com/timlau/yumex-ng/assets/11287837/e407edb8-f84e-429b-8a95-293aedc5e1e2)
![Screenshot from 2023-06-23 19-19-57](https://github.com/timlau/yumex-ng/assets/11287837/d7f51c47-4d73-4641-b13e-573f8e704235)
![Screenshot from 2023-06-23 19-20-02](https://github.com/timlau/yumex-ng/assets/11287837/c8b17e75-5af2-4112-b50b-4158613d7baf)

**Comment by timlau** [comment]
Thanks for reporting.
It should properly not be an option to select a location, if there is no available remote.
but it look like the source selection is not reset if there is no available remotes

**Comment by GloriousEggroll** [comment]
Just confirming https://github.com/timlau/yumex-ng/commit/16b8221720eba0ea44a93a074129d0f60fdcf21b does indeed fix the issue. Thanks again!
