### ISSUE TITLE
Select all files to update and  be able to delete software

### ISSUE THREAD

**Issue by Tuxman2** [timlau/yumex-ng#43]
Hello,

Can you add these features ?

- Select all files to update (see it in dnfdragora). Via an Option in the menu.
-  Be able to delete the software (one or more) with its dependencies (if it is possible).

Thanks.

**Comment by timlau** [comment]
To select All Updates

1. Show available updates ( Alt - U)
2. Select All (Ctrl-A or right click on selection header and choose "Select All" from menu)
3. Apply Updates (Ctrl - Enter)

![Screenshot from 2023-08-14 08-01-51](https://github.com/timlau/yumex-ng/assets/283985/e338756a-4640-44e4-8a06-6fd58dfb64eb)

**Comment by timlau** [comment]
To delete a package, just select a installed package and it will be added to the queue for deletion incl. dependencies.

[Screencast from 2023-08-14 08-09-31.webm](https://github.com/timlau/yumex-ng/assets/283985/a45a84f9-eb46-4e8d-b770-a471079bbb28)

**Comment by Tuxman2** [comment]
Thanks.

I will try it.

**Comment by Tuxman2** [comment]
Hi,

Ok, it works. :-)

Hope to see group support and others features soon.

Thanks.

**Comment by timlau** [comment]
Group support will not planned currently, maybe it will be added over time, when the group API in DNF5 is more set in stone and if I find good user cases for it, I also never use it myself and don't think that is useful on daily basic for many users.
I don't want to spend a lot of time to design and implement features that is not used by many people
