### ISSUE TITLE
Package filter > Updates list ignores repository priority.

### ISSUE THREAD

**Issue by GloriousEggroll** [timlau/yumex-ng#50]
Ex:
I have wlroots5 package hosted in a custom copr repository. I give this repository priority=50:
```
[nobara-baseos-$releasever]
name=nobara-baseos-$releasever
#baseurl=https://download.copr.fedorainfracloud.org/results/gloriouseggroll/nobara-39/fedora-$releasever-$basearch/
mirrorlist=https://mirrors.nobaraproject.org/baseos
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-nobara-baseos-pubkey-$releasever-$basearch
repo_gpgcheck=0
enabled=0
enabled_metadata=1
priority=50
```

This means any other repository, regardless of if they provide a newer version of wlroots50, should be ignored. However, yumex-ng reports the version from Fedora's `updates` repository as an available upgrade because it is a newer version, regardless of the `updates` repository priority being lower. This can of course result in breakage on the system if installed.

**Comment by timlau** [comment]
What backend are you using ?

I just get the packages from dfn4/dnf5 API, i don't do any thing special regarding the repo setup.

The problem can be that using the DNF API, don't give tne same results as DNF CLI because of plugins.

**Comment by GloriousEggroll** [comment]
Im currently using DNF5 but it also happens on DNF 3/4. KDE Discover and gnome-software have the same issue. Then again they generally expect repos to just have the latest versions at all times, none of them take repo priority into consideration either.
