### ISSUE TITLE
Repositories won't enable (dnf5 version)

### ISSUE THREAD

**Issue by Spaceboy60** [timlau/yumex-ng#55]
So I enable the repositories I want enabled, exit the program. But after restart the repositories I've enabled are still showing as disabled.

(process:146449): Gtk-WARNING **: 09:04:05.292: Theme parser error: gtk-dark.css:6146:10-13: Expected a valid color.

(process:146449): Gtk-WARNING **: 09:04:05.292: Theme parser error: gtk-dark.css:6154:10-13: Expected a valid color.

(process:146449): Gtk-WARNING **: 09:04:05.292: Theme parser error: gtk-dark.css:6217:10-13: Expected a valid color.

(process:146449): Gtk-WARNING **: 09:04:05.292: Theme parser error: gtk-dark.css:6222:10-13: Expected a valid color.

(process:146449): Gtk-WARNING **: 09:04:05.293: Theme parser error: gtk-dark.css:6341:10-13: Expected a valid color.

(process:146449): Gtk-WARNING **: 09:04:05.293: Theme parser error: gtk-dark.css:6346:10-13: Expected a valid color.

(process:146449): Gtk-WARNING **: 09:04:05.294: Theme parser error: gtk-dark.css:7084:21-28: Expected a valid color.

(process:146449): Gtk-WARNING **: 09:04:05.294: Theme parser error: gtk-dark.css:7089:21-28: Expected a valid color.

(process:146449): Gtk-WARNING **: 09:04:05.295: Theme parser error: gtk-dark.css:7243:21-28: Expected a valid color.

(process:146449): Gtk-WARNING **: 09:04:05.295: Theme parser error: gtk-dark.css:7249:21-28: Expected a valid color.

(process:146449): Adwaita-WARNING **: 09:04:05.320: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
09:04:05 DEBUG : (yumex) -  Version:  4.99.4-git20240421 (DNF5)
09:04:05 DEBUG : (yumex) -  executable : /usr/bin/yumex
09:04:05 DEBUG : (yumex) -  commmand-line : Namespace(debug=False, exit=False)
09:04:05 DEBUG : (yumex) -  set_need_attetion (flatpak): state: False 
09:04:05 DEBUG : (yumex) -  window-height: 700
09:04:05 DEBUG : (yumex) -  window-width: 1000
09:04:05 DEBUG : (yumex) -  fullscreened: False
09:04:05 DEBUG : (yumex) -  maximized: False
09:04:05 DEBUG : (yumex) -  SIGNAL: emit package-filter-changed: installed
09:04:05 DEBUG : (yumex) -  SIGNAL: package filter changed : installed
09:04:05 DEBUG : (yumex) -  Loading packages : installed
09:04:05 DEBUG : (yumex) -  >> Running async job : get_packages_by_filter.
09:04:05 DEBUG : (yumex) -  search changed : 
09:04:07 DEBUG : (yumex) -  << Completed async job : get_packages_by_filter.
09:04:07 DEBUG : (yumex) -  >> starting add_packages_to_store
09:04:07 DEBUG : (yumex) -  Adding packages to store
09:04:07 DEBUG : (yumex) -   --> sorting by : name
09:04:08 DEBUG : (yumex) -   --> number of packages : 2159
09:04:08 DEBUG : (yumex) -  << add_packages_to_store took 0.3083 sec
09:04:08 DEBUG : (yumex) -  SIGNAL: emit selection_changed: abattis-cantarell-fonts-0:0.301-12.fc40.noarch
09:04:08 DEBUG : (yumex) -  Window: package selection changed : abattis-cantarell-fonts-0:0.301-12.fc40.noarch
09:04:08 DEBUG : (yumex) -  >> Running async job : get_package_info.
09:04:08 DEBUG : (yumex) -  << Completed async job : get_package_info.

**Comment by timlau** [comment]
Repositories in yumex-ng preferences is currently just to show the ones selected by the system, not to change the selected ones.
I can see the UI is a little misleading as you can change the switches but has no effect.

I will change so the switches so they can't be changed, for now

**Comment by timlau** [comment]
cd054dc527b0f0e06d09f0191ba28e4c1e883d24

**Comment by timlau** [comment]
Add feature #56 to track this

**Comment by timlau** [comment]
closing this issue, feature is tracked by another feature issue
