### ISSUE TITLE
Updates  not found

### ISSUE THREAD

**Issue by edpil02** [timlau/yumex-ng#57]
dnf5 update finds updates yumex not (latest copr build).
![update](https://github.com/timlau/yumex-ng/assets/43163048/82c740b0-89bf-41f0-8913-883900c12b73)

**Comment by timlau** [comment]
It is because that yumex use dnf5 in user context to show packages and sometime the metadata don't get refreshed at the same time.

```
dnf5 check-update --refresh
sudo dnf5 check-update --refresh
```
should force update both, I have seen examples of where i have to run these commands twice to make sure they are in sync.

**Comment by timlau** [comment]
The problem is there is no public API to force metadata refresh in the dnf5 api and dnf5daemon api used by yumex

I would be best to only use the dnf5daemon API, but it will properly make package loading and searching much slower
