### ISSUE TITLE
Crash on wayland

### ISSUE THREAD

**Issue by edpil02** [timlau/yumex-ng#59]
Since a  week  ago yumex crashes with this error message:

16:19:06 DEBUG : (yumex) -  >> Running async job : get_package_info.
16:19:06 DEBUG : (yumex) -  << Completed async job : get_package_info.
Gdk-Message: 16:19:06.925: Error flushing display:  broken pipe

Being on kde I installed and tested other GTK4 applications and I have no crashes.

GDK_BACKEND=x11  yumex help.

**Comment by edpil02** [comment]
It's not a yumex  error :
[3149099.535] wl_display@1.error(wp_linux_drm_syncobj_surface_v1@82, 4, "explicit sync is used, but no acquire point is set")
Gdk-Message: 10:25:58.942: Error 71 (Erreur de protocole) dispatching to Wayland display.

Thanks

**Comment by timlau** [comment]
Yumex just use gtk4 & libadwaita framework, so there is nothing yumex can do about there kind of issues.
 I have no problems with Gnome & Wayland.
