### ISSUE TITLE
Request: Better way to display flatpak search results

### ISSUE THREAD

**Issue by GloriousEggroll** [timlau/yumex-ng#60]
Currently when you go to install a new flatpak and search for the flatpak you want, the results display like this:

![Screenshot_20240529_104841](https://github.com/timlau/yumex-ng/assets/11287837/ecd945eb-8be1-4979-9c07-87763419d4bb)

If you hover over where it says 1/3 it says to use ctrl+g or shift+ctrl+g to toggle.

For me the toggles don't work, but rather than fixing the toggles I feel instead this whole area (the section displaying the results) should be changed to a scroll window with a list of the search results. We've been shipping yumex-ng in Nobara for a while now and I've found many users don't utilize it for flatpaks because of this.  Also possibly make the window bigger and allow flatpak descriptions to be displayed within the results.

One good example of how this is handled would be the flatpak app "warehouse" which is also another flatpak management tool:

![Screenshot_20240529_105544](https://github.com/timlau/yumex-ng/assets/11287837/5d6fc1e9-a87d-41f0-8978-1dea40b87842)

![Screenshot_20240529_105629](https://github.com/timlau/yumex-ng/assets/11287837/bff99913-f0a2-4c62-96a1-1617e8cf2e6f)

Note: You can't see it in the screenshot but the search results are scrollable up/down:

![Screenshot_20240529_105701](https://github.com/timlau/yumex-ng/assets/11287837/52155457-b273-42c9-8db0-a334ce17e412)

**Comment by timlau** [comment]
It is on my todo list to make the flatpak installer better with a some kind of list.

Ctrl-G, Shift-Ctrl-G only work when the focus is on the search entry, if you click on the results, it will not work

Short term is will make the current chosen title so it cant get the focus

**Comment by timlau** [comment]
I have created a new flatpak search dialog there is much better than the old one.

![image](https://github.com/timlau/yumex-ng/assets/283985/afc6df1d-1984-46b6-bbad-c1bf48f36a4e)

**Comment by GloriousEggroll** [comment]
looks like im hitting an error with latest git:
```
14:14:00 CRITICAL: (yumex) -  Uncaught exception: g-io-error-quark: Error opening file /home/tcrider/.local/share/flatpak/appstream/umu-repo/x86_64/active/appstream.xml.gz: No such file or directory (1)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yumex/ui/window.py", line 391, in on_actions
    self.flatpak_view.search()
  File "/usr/lib/python3.12/site-packages/yumex/ui/flatpak_view.py", line 93, in search
    flatpak_search = YumexFlatpakSearch(self.presenter)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yumex/ui/flatpak_search.py", line 60, in __init__
    self.setup_location()
  File "/usr/lib/python3.12/site-packages/yumex/ui/flatpak_search.py", line 79, in setup_location
    self.on_location_selected()
  File "/usr/lib/python3.12/site-packages/yumex/ui/flatpak_search.py", line 86, in on_location_selected
    self.app_search.add_installation(self.backend.get_installation(fp_location))
  File "/usr/lib/python3.12/site-packages/yumex/backend/flatpak/search.py", line 91, in add_installation
    self.add_remote(remote, inst)
  File "/usr/lib/python3.12/site-packages/yumex/backend/flatpak/search.py", line 98, in add_remote
    self.remotes[remote_name] = self._load_appstream_metadata(remote)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yumex/backend/flatpak/search.py", line 105, in _load_appstream_metadata
    metadata.parse_file(
gi.repository.GLib.GError: g-io-error-quark: Error opening file /home/tcrider/.local/share/flatpak/appstream/umu-repo/x86_64/active/appstream.xml.gz: No such file or directory (1)
14:14:00 DEBUG : (yumex) -  traceback written to /home/tcrider/.local/share/yumex/traceback_06-10-2024_141400.txt
```

**Comment by GloriousEggroll** [comment]
nevermind -- its due to a local repo i had for another project ive been working on that has since been removed

**Comment by timlau** [comment]
flatpack installer replaced with better one in current release
