### ISSUE TITLE
Request: small improvement suggestions on Packages listing section

### ISSUE THREAD

**Issue by GloriousEggroll** [timlau/yumex-ng#73]
In the title bar:
![yumextb](https://github.com/timlau/yumex-ng/assets/11287837/43256d66-95de-4711-bedb-42aaedd582c7)

It would be nice if:

1. Clicking the checkmark checked or unchecked all boxes
2. Clicking any of the other titles sorted the list alphabetically by that column.

For example if I clicked the 'Repository' column title it would sort the listings by repository alphabetically.

At bare minimum I feel clicking the checkmark for the 'select' column title should select/unselecting all items, it's generally an expected action for most users.

**Comment by timlau** [comment]
I had some problem making it work, when i made it, so currently there is a right click menu on the selection column to select/de-select all and keyboard shortcut Ctrl-A / Shift-Ctrl-A to select/de-select all

**Comment by timlau** [comment]
The main problem is there is not signal triggered when the user click on the column header in a [Gtk.ColumnViewColumn](https://docs.gtk.org/gtk4/class.ColumnViewColumn.html)
So there is no way to assign actions to the column click

**Comment by GloriousEggroll** [comment]
ah thats a bummer. well if its not possible it is what it is, ill just close this
