### ISSUE TITLE
yumex_updater_systray crash at boot

### ISSUE THREAD

**Issue by g6avk** [timlau/yumex-ng#78]
I have been testing the last few builds that have the yumex updater (thanks for adding this)
However, since PR #75 the mem leak fix I get a crash on every reboot, once the system is up it works fine.
I am fairly sure it never happened before the mem leak fix.

I will attach a BT and hope it will be of use.

Operating System: Fedora Linux 40
KDE Plasma Version: 6.1.0
Kernel Version: 6.9.6-200.fc40.x86_64 (64-bit)
Graphics Platform: Wayland

[yumex_bt.txt](https://github.com/user-attachments/files/15937830/yumex_bt.txt)

**Comment by timlau** [comment]
Works fine for me in Gnome / Wayland.

Can you please add the log form the yumex-updater
```
journalctl --user-unit=yumex-updater-systray -n 100 > yumex-updater.log
```

**Comment by timlau** [comment]
Try building some local rpms from git to see if it makes any difference
```bash
make inst-deps
make test-update
```

**Comment by g6avk** [comment]
Here is the output of journalctl --user-unit=yumex-updater-systray -n 100 > yumex-updater.log

[yumex-updater.log](https://github.com/user-attachments/files/16018526/yumex-updater.log)

This was tested from your current rpm released today.

**Comment by g6avk** [comment]
I built new rpms today with the latest git changes, and it looks like the crash problem with the  systray updater (with KDE) is fixed now.
I'll keep and eye on it for a few days to be sure.

**Comment by g6avk** [comment]
Fixed, no crash at all now. Thanks for fixing this 👍🏻
