### ISSUE TITLE
Error on notification tray

### ISSUE THREAD

**Issue by andreluizmg** [timlau/yumex-ng#83]
dont know much of the problem , just reporting might help...
When clicking on "open package manager"
![image](https://github.com/timlau/yumex-ng/assets/26634756/b7b47e36-425c-411e-9653-db2c034056b2)
"Error in loading packages filesystem error: cannot create directory: Não é um diretório [/home/andre/.cache/libdnf5/ temporary_files.toml/attrs]"
![image](https://github.com/timlau/yumex-ng/assets/26634756/98bfca8c-6956-4094-ae02-6e4c19108c4e)

Just reporting, but I would like to have on settings a way to remove notification since its duplicated with system updates notification..

nevermind i managed to remove package for that 
![image](https://github.com/timlau/yumex-ng/assets/26634756/ff47b6d8-500e-48c8-85c4-8a61066cb1e5)

**Comment by timlau** [comment]
As you all ready found out, you can just remove the yumex-dnf5-updater-systray if you don't want the yumex systray applet.

I have not seen the error about being able to create the libdnf5 cache dir, it can be a race condition where both yumex and the updater is trying to refresh at the same time and and the files get locked.

But thanks for reporting.
