### ISSUE TITLE
Flatpak search not working

### ISSUE THREAD

**Issue by TormStorm** [timlau/yumex-ng#97]
Trying to search for a Flatpak gives no results, only an install button appears which throws an error when pressed. Tested in Yum Extender 5.0.1 (DNF4) on a fresh install of Nobara 40

![image](https://github.com/user-attachments/assets/d44512ce-d366-4fd5-8bdd-e52aeeb4220d)

![image](https://github.com/user-attachments/assets/1f5f24f2-b99b-406e-a8fd-aaf2e34b47f6)

**Comment by seadx6-neo** [comment]
I have the same exact issue in my install

**Comment by Marquak** [comment]
Ditto, hope this gets addressed soon!

**Comment by Nobnab** [comment]
Same problem here

**Comment by timlau** [comment]
The search only works on the flatpak repositories enabled of the current location, so if flathub is not added to user location, then you will no results.
Try change to system location or make sure that flathub is added to user location

**Comment by timlau** [comment]
I will add some information in a future release to show what repositories there is used for the search and make the install button not work if no flatpak is selected for installation

**Comment by Nobnab** [comment]
I use nobara and what else I noticed after a little experimentation:
If the system language is set to english everything works fine, if i set it to german i get the above mentioned problems. and what i also noticed: if i want to uninstall an already installed flatpak in german language i get the message: “canceled by user”. I switched to english and everything works again.

Perhaps the problem also lies with Nobara itself

**Comment by timlau** [comment]
I can re-produce the issue with flatpak-search install is not working on non English locale.
Created  a new issue to track that (#98)

**Comment by timlau** [comment]
disabled flathub remote using
```
flatpak remote-modify flathub --disable --user

❯ flatpak remotes --show-disabled 
Navn           Tilvalg
fedora         system,oci
fedora-testing system,disabled,oci
flathub        system,filtered
flathub        user,disabled

```

![Skærmbillede fra 2024-07-25 19-15-57](https://github.com/user-attachments/assets/84bdfa01-b8b3-48e5-922c-8ec464ea2fb2)
![Skærmbillede fra 2024-07-25 19-16-10](https://github.com/user-attachments/assets/835eba5a-2fe4-40a2-9cfb-468e0f9e7a55)

**Comment by timlau** [comment]
![Skærmbillede fra 2024-07-25 20-28-40](https://github.com/user-attachments/assets/01ad1a7e-51a5-4efd-b3bc-6075b0333e69)
